### ISSUE TITLE
No Loading states and images are in out of scope folder

### ISSUE THREAD

**Issue by ronny8877** [Rishab-Rana/Movie-App-in-React-with-API#1]
![bitmoji](https://sdk.bitmoji.com/render/panel/cf5cacb9-2c96-4fec-8a21-6fa60bf09f96-dfb0bf5c-ca39-41be-8163-8fd8be5e8b78-v1.png?transparent=1&palette=1&width=246)![bitmoji](https://sdk.bitmoji.com/render/panel/cf5cacb9-2c96-4fec-8a21-6fa60bf09f96-dfb0bf5c-ca39-41be-8163-8fd8be5e8b78-v1.png?transparent=1&palette=1&width=246)

**Comment by Rishab-Rana** [comment]
done
